"use client";

import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import Link from "next/link";
import { MAX_CART_LINE_QUANTITY, useCart } from "@/components/cart/cart-provider";
import { calculateItemUnitTotal, formatPhp } from "@/lib/commerce";
import { primaryButtonClassName, secondaryButtonClassName } from "@/components/ui/button";
import { cn } from "@/lib/cn";

export function CartPageContent() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  if (items.length === 0) return <section className="rounded-card border border-border bg-surface px-6 py-16 text-center"><ShoppingBag className="mx-auto text-brand" size={42} /><h1 className="mt-5 font-display text-3xl">Your cart is empty</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Build a box and it will wait here for checkout.</p><Link href="/our-creations" className={cn(primaryButtonClassName, "mt-7")}>Build a box</Link></section>;
  return <div className="grid items-start gap-8 lg:grid-cols-[1fr_22rem]"><section><h1 className="font-display text-4xl">Your cart</h1><p className="mt-2 text-muted-foreground">Review each box configuration before pickup checkout.</p><div className="mt-8 space-y-4">{items.map((item) => {
    const unitTotal = calculateItemUnitTotal(item.boxPrice, item.extraCoatingCharge, item.addonQuantity, item.addonPrice);
    const coatings = Object.entries(item.coatingCounts).filter(([, count]) => count > 0).map(([id, count]) => `${item.coatingNames[id]} × ${count}`).join(", ");
    return <article key={item.id} className="rounded-card border border-border bg-surface p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold uppercase text-subtle-foreground">Box of {item.pieceCount}</p><h2 className="mt-1 font-display text-2xl">Chocolate Litaw box</h2><p className="mt-2 text-sm text-muted-foreground">{coatings}</p>{item.addonQuantity && item.addonName ? <p className="mt-1 text-sm text-muted-foreground">{item.addonName} × {item.addonQuantity}</p> : null}</div><strong className="font-display text-xl">{formatPhp(unitTotal * item.quantity)}</strong></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-4"><div className="flex items-center gap-3"><button aria-label="Decrease quantity" type="button" disabled={item.quantity <= 1} onClick={() => updateQuantity(item.id, item.quantity - 1)} className="flex size-11 items-center justify-center rounded-full bg-surface-muted disabled:cursor-not-allowed disabled:opacity-40"><Minus size={16} /></button><span className="min-w-5 text-center font-bold">{item.quantity}</span><button aria-label={`Increase quantity, maximum ${MAX_CART_LINE_QUANTITY}`} type="button" disabled={item.quantity >= MAX_CART_LINE_QUANTITY} onClick={() => updateQuantity(item.id, item.quantity + 1)} className="flex size-11 items-center justify-center rounded-full bg-surface-muted disabled:cursor-not-allowed disabled:opacity-40"><Plus size={16} /></button></div><button type="button" onClick={() => removeItem(item.id)} className="flex min-h-11 items-center gap-2 rounded-full px-3 text-sm font-bold text-danger-foreground hover:bg-danger-background"><Trash2 size={17} />Remove</button></div></article>;
  })}</div></section><aside className="rounded-card border border-border bg-surface p-6 lg:sticky lg:top-6"><h2 className="font-display text-2xl">Summary</h2><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-muted-foreground"><dt>Subtotal</dt><dd>{formatPhp(subtotal)}</dd></div><div className="flex justify-between border-t border-border pt-4 text-lg font-bold"><dt>Total</dt><dd>{formatPhp(subtotal)}</dd></div></dl><Link href="/checkout" className={cn(primaryButtonClassName, "mt-6 w-full")}>Proceed to checkout</Link><Link href="/our-creations" className={cn(secondaryButtonClassName, "mt-3 w-full")}>Continue shopping</Link></aside></div>;
}
