import { CheckCircle2, Circle, MapPin, PackageCheck, Star } from "lucide-react";
import Link from "next/link";
import { getMockOrder } from "@/lib/mock-orders";
import { formatPhp } from "@/lib/commerce";
import { StatusBadge } from "@/components/ui/status-badge";

export function OrderDetailView({ orderId }: { orderId: string }) {
  const order = getMockOrder(orderId);
  if (!order) return <section className="rounded-card border border-border bg-surface p-8 text-center"><h2 className="font-display text-2xl">Order not found</h2><p className="mt-2 text-sm text-muted-foreground">This mock order does not exist or is not available to this customer.</p><Link href="/orders" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-brand px-6 font-bold text-surface">Back to orders</Link></section>;
  const complete = order.status === "COMPLETED";
  const canCancel = ["PENDING_PAYMENT", "PAID", "CONFIRMED"].includes(order.status);
  const steps = ["Order placed", "Payment confirmed", "Preparing", "Ready for pickup", "Completed"];
  const progress = complete ? 5 : order.status === "PREPARING" ? 3 : 2;
  return <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><section className="rounded-card border border-border bg-surface p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase text-subtle-foreground">Order number</p><h2 className="mt-1 font-display text-2xl">#{order.id}</h2></div><StatusBadge status={order.status} /></div><ol className="mt-8 space-y-5">{steps.map((label, index) => <li key={label} className="flex gap-4">{index < progress ? <CheckCircle2 className="mt-0.5 shrink-0 text-success-foreground" size={21} /> : <Circle className="mt-0.5 shrink-0 text-border" size={21} />}<div><h3 className="text-sm font-bold">{label}</h3><p className="mt-1 text-xs text-muted-foreground">{index < progress ? "Completed" : "Waiting for an update"}</p></div></li>)}</ol></section><section className="rounded-card border border-border bg-surface p-6 sm:p-8"><h2 className="font-display text-2xl">Items</h2><div className="mt-5 flex justify-between gap-5"><div><h3 className="font-display text-lg">Chocolate Litaw · {order.box}</h3><p className="mt-1 text-sm text-muted-foreground">{order.coatings}</p></div><strong>{formatPhp(order.total)}</strong></div></section></div><aside className="space-y-5"><section className="rounded-card border border-border bg-surface p-6"><div className="flex items-center gap-3"><MapPin className="text-brand" size={21} /><h2 className="font-display text-xl">Campus pickup</h2></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{order.pickup}</p></section><section className="rounded-card border border-border bg-surface p-6"><div className="flex items-center gap-3"><PackageCheck className="text-brand" size={21} /><h2 className="font-display text-xl">Payment summary</h2></div><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Payment</dt><dd>Paid</dd></div><div className="flex justify-between border-t border-border pt-3 font-bold"><dt>Total</dt><dd>{formatPhp(order.total)}</dd></div></dl></section>{complete && !order.reviewed ? <Link href={`/orders/${order.id}/review`} className="flex min-h-11 items-center justify-center gap-2 rounded-full bg-brand px-6 text-sm font-bold text-surface"><Star size={17} />Leave a review</Link> : null}{complete && order.reviewed ? <p className="rounded-control bg-success-background p-4 text-sm font-bold text-success-foreground">You already reviewed this order.</p> : null}{canCancel ? <button type="button" disabled className="min-h-11 w-full rounded-full border border-brand px-6 text-sm font-bold text-brand opacity-60">Cancellation available after backend setup</button> : <p className="rounded-control bg-surface-muted p-4 text-xs leading-5 text-muted-foreground">Self-cancellation is unavailable once preparation begins.</p>}</aside></div>;
}
