"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _tsokolitaw_page from './tsokolitaw-page.bones.json'

configureBoneyard({"color":"#eadfce","animate":"shimmer","shimmerColor":"#f8f0e5","speed":"2s"})

registerBones({
  "tsokolitaw-page": _tsokolitaw_page,
})
